openapi: 3.1.0
info:
  title: APIFiddle Sample Definition
  description: Example workspace
  version: 0.0.0
paths:
  /api/v1/bookings:
    post:
      operationId: createABookingAtomically
      tags:
        - bookings
      summary: Create a Booking atomically
      responses:
        "201":
          description: The request was successful, and a new resource was created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      booking:
                        $ref: "#/components/schemas/Bookings"
                    required:
                      - booking
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/Not Found"
        "500": &a1
          description: The server encountered an unexpected condition that prevented it
            from fulfilling the request. Report the issue to the support team if
            it persists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                    required:
                      - code
                      - message
                required:
                  - error
      description: >-
        Creates a booking record and finalizes the associated reservation within
        a single atomic operation.


        The endpoint validates the provided booking data and executes all
        database operations inside a transaction.

        Upon successful booking creation, the related reservation is
        transitioned to the `completed` state.


        In case of failure, all changes are rolled back to preserve consistency.
      requestBody:
        required: true
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                courseId:
                  type: string
                userId:
                  type: string
                reservationId:
                  type: string
                slots:
                  type: string
                transactionId:
                  type: string
                price:
                  type: string
              required:
                - courseId
                - userId
                - reservationId
                - slots
                - transactionId
                - price
    get:
      operationId: retrieveBookingsWithOptionalFilters
      tags:
        - bookings
      summary: Retrieve bookings with optional filters
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      bookings:
                        type: array
                        items:
                          $ref: "#/components/schemas/Bookings"
                    required:
                      - bookings
                required:
                  - data
        "500": *a1
      parameters:
        - in: query
          name: userId
          required: false
          style: form
          description: ID of the user holding the bookings
          explode: true
          schema:
            type: string
          allowReserved: false
      description: |-
        Returns a list of bookings from the data store.

        The endpoint supports optional query parameters to filter the results.
        When no filters are provided, all bookings are returned.

        Currently supported filters:
        - `userId`:  returns only bookings associated with the specified user.
  /api/v1/courses/{id}:
    get:
      operationId: getCourseById
      tags:
        - courses
      summary: Get course by Id
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      course:
                        $ref: "#/components/schemas/Course"
                    required:
                      - course
                required:
                  - data
        "400":
          $ref: "#/components/responses/Bad Request"
        "404":
          $ref: "#/components/responses/Not Found"
  /api/v1/reservations:
    get:
      operationId: getReservations
      tags:
        - reservations
      summary: Get Reservations
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      reservations:
                        type: array
                        items:
                          $ref: "#/components/schemas/Reservation"
                    required:
                      - reservations
                required:
                  - data
        "500":
          $ref: "#/components/responses/InternalServerErrror"
      parameters: []
      description: desc
    post:
      operationId: createAReservationAtomically
      tags:
        - reservations
      summary: Create a Reservation atomically
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/Bad Request"
        "404":
          $ref: "#/components/responses/Not Found"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/Internal Server Error"
      requestBody:
        required: true
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  type: string
              required:
                - test
      parameters: []
      description: desc
  /api/v1/reservations/cleanup:
    patch:
      operationId: cleanupExpiredReservations
      tags:
        - reservations
      summary: Cleanup expired reservations
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      processed:
                        type: number
                      cleaned:
                        type: number
                      failed:
                        type: number
                    required:
                      - processed
                      - cleaned
                      - failed
                required:
                  - data
  /api/v1/reservations/{id}:
    get:
      operationId: getReservationById
      tags:
        - reservations
      summary: Get reservation by id
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                required:
                  - data
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
      description: desc
  /api/v1/reservations/{id}/cancel:
    patch:
      operationId: cancelAReservation
      tags:
        - reservations
      summary: Cancel a Reservation
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          $ref: "#/components/responses/No Content"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerErrror"
      description: desc
  /api/v1/courses:
    get:
      operationId: getAllCourses
      tags:
        - courses
      summary: Get all courses
      responses:
        "200":
          description: The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      courses:
                        type: array
                        items:
                          $ref: "#/components/schemas/Course"
                    required:
                      - courses
                required:
                  - data
        "500":
          description: The server encountered an unexpected condition that prevented it
            from fulfilling the request. Report the issue to the support team if
            it persists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                    required:
                      - code
                      - message
                required:
                  - error
      parameters: []
      description: desc
components:
  responses:
    BadRequest:
      description: The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
            required:
              - error
    Not Found:
      description: The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
            required:
              - error
    Bad Request:
      description: The server could not understand the request due to invalid syntax.
        The client should modify the request and try again.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                  required:
                    - message
            required:
              - message
    InternalServerErrror:
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    Conflict:
      description: The request could not be completed due to a conflict with the
        current state of the resource. Resolve the conflict and try again.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    Internal Server Error:
      description: The server encountered an unexpected condition that prevented it
        from fulfilling the request. Report the issue to the support team if it
        persists.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    Created:
      description: The request was successful, and a new resource was created.
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
            required:
              - data
    NotFound:
      description: The server cannot find the requested resource. The endpoint may be
        invalid or the resource may no longer exist.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
    No Content:
      description: The request was successful, but there is no content to return in
        the response.
      content:
        application/json:
          schema:
            type: "null"
  schemas:
    Bookings:
      type: object
      properties:
        course:
          type: string
        price:
          type: string
        transactionId:
          type: string
        status:
          type: string
          enum:
            - confirmed
            - cancelled
        slots:
          type: array
          items:
            type: string
        reservation:
          type: string
        user:
          type: string
        _id:
          type: string
      required:
        - course
        - price
        - transactionId
        - status
        - slots
        - reservation
        - user
        - _id
      description: desc
    Course:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        slots:
          type: array
          items:
            type: object
            properties:
              start:
                type: string
              end:
                type: string
              capacity:
                type: number
              available:
                type: number
            required:
              - start
              - end
              - capacity
              - available
        open:
          type: boolean
        priceOptions:
          type: array
          items:
            type: object
            properties:
              numberSlots:
                type: number
              price:
                type: string
            required:
              - numberSlots
              - price
        _id:
          type: string
      required:
        - name
        - description
        - slots
        - open
        - priceOptions
        - _id
      description: desc
    Reservation:
      type: object
      properties:
        course:
          type: string
        user:
          type: string
        slots:
          type: array
          items:
            type: string
        status:
          type: string
          enum:
            - held
            - completed
            - cancelled
            - expired
        expiration:
          type: string
        _id:
          type: string
      required:
        - course
        - user
        - slots
        - status
        - expiration
        - _id
      description: dee
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string
tags:
  - name: bookings
  - description: ""
    name: courses
  - name: reservations
